# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "wkhtmltopdf-heroku-edge"
  s.version = "0.12.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brad Phelan"]
  s.date = "2015-02-17"
  s.description = "wkhtmltopdf binaries heroku"
  s.email = "bradphelan@xtargets.com"
  s.executables = ["wkhtmltopdf-linux-amd64"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.mdown"
  ]
  s.files = [
    "LICENSE.txt",
    "README.mdown",
    "VERSION",
    "bin/wkhtmltopdf-linux-amd64",
    "lib/wkhtmltopdf-heroku-edge.rb",
    "wkhtmltopdf-heroku-edge.gemspec"
  ]
  s.homepage = "http://github.com/bradphelan/wkhtmltopdf-heroku"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "wkhtmltopdf binaries for heroku"
end

